"""Initial schema with multi-location support

Revision ID: 9f48fc54de79
Revises: 
Create Date: 2026-01-03 01:41:01.357981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f48fc54de79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'stock_quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('ingredients', 'min_stock',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('modifiers', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_orders_location_id'), 'orders', ['location_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'locations', ['location_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_location_id'), table_name='orders')
    op.alter_column('orders', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'modifiers')
    op.drop_column('order_items', 'variant_id')
    op.alter_column('ingredients', 'min_stock',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('ingredients', 'stock_quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
